name: toistot_talteen
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.15+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.4.3
  cached_network_image: 3.2.1
  cloud_firestore: 4.2.0
  cloud_firestore_platform_interface: 5.9.1
  cloud_firestore_web: 3.1.1
  cloud_functions: 4.0.6
  cloud_functions_platform_interface: 5.1.25
  cloud_functions_web: 4.3.14
  csv: 5.0.1
  dropdown_button2: 2.0.0
  easy_debounce: 2.0.1
  emoji_flag_converter: 1.1.0
  expandable: 5.0.1
  file_picker: 5.2.6
  firebase_analytics: 10.0.7
  firebase_analytics_platform_interface: 3.3.15
  firebase_analytics_web: 0.5.1+6
  firebase_auth: 4.2.0
  firebase_auth_platform_interface: 6.11.4
  firebase_auth_web: 5.2.0
  firebase_core: 2.4.0
  firebase_core_platform_interface: 4.5.2
  firebase_core_web: 2.0.2
  firebase_crashlytics: 3.0.7
  firebase_crashlytics_platform_interface: 3.3.8
  firebase_messaging: 14.1.4
  firebase_messaging_platform_interface: 4.2.8
  firebase_messaging_web: 3.2.9
  firebase_remote_config: 3.0.7
  firebase_storage: 11.0.7
  firebase_storage_platform_interface: 4.1.25
  firebase_storage_web: 3.3.17
  fl_chart: 0.55.0
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_heatmap_calendar: ^1.0.5
  flutter_keyboard_visibility: 5.2.0
  flutter_plugin_android_lifecycle: 2.0.9
  flutter_secure_storage: 8.0.0
  flutter_spinkit: 5.1.0
  flutter_stripe: 9.1.1
  flutter_stripe_web: 4.0.1
  flutter_svg: 2.0.4
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 3.1.0
  google_fonts: 4.0.3
  google_mobile_ads: 2.3.0
  google_sign_in: 6.0.2
  google_sign_in_android: 6.1.8
  google_sign_in_ios: 5.6.1
  google_sign_in_platform_interface: 2.4.0
  google_sign_in_web: 0.11.0+2
  image_picker: 0.8.5+3
  image_picker_android: 0.8.5+3
  image_picker_for_web: 2.1.10
  image_picker_ios: 0.8.6+1
  image_picker_platform_interface: 2.6.2
  intl: 0.17.0
  json_path: 0.4.1
  json_serializable: 6.6.1
  lottie: 1.2.1
  mask_text_input_formatter: 2.4.0
  mime_type: 1.0.0
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  photo_view: 0.14.0
  plugin_platform_interface: 2.1.3
  provider: 6.0.4
  purchases_flutter: 4.10.2
  rxdart: 0.27.7
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  smooth_page_indicator: 1.0.1
  sqflite: 2.2.6
  stripe_android: 9.1.0
  stripe_ios: 9.1.0
  stripe_platform_interface: 9.1.0
  substring_highlight: 1.0.33
  synchronized: 3.1.0
  table_calendar: 3.0.6
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  video_player: 2.6.0
  video_player_android: 2.4.3
  video_player_avfoundation: 2.4.2
  video_player_platform_interface: 6.1.0
  video_player_web: 2.0.15
  webview_flutter: 4.0.5
  webview_flutter_android: 3.3.1
  webview_flutter_platform_interface: 2.0.2
  webview_flutter_wkwebview: 3.1.1
  webviewx_plus: 0.3.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  analyzer: 5.10.0
  build_runner: 2.3.3
  built_value_generator: 8.4.3
  flutter_launcher_icons: 0.12.0

  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  fonts:
    - family: 'Satoshi'
      fonts:
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Satoshi-Regular.otf
        - asset: assets/fonts/Satoshi-Italic.otf
          style: italic
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-BlackItalic.otf
          weight: 900
          style: italic


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
